stages:
  - merge

custom-merge-script:
  stage: merge
  before_script:
    - export MERGE_LOG="merge_${CI_COMMIT_SHORT_SHA}_${CI_JOB_ID}.log"
    - echo "=== ЛОГ MERGE ===" > $MERGE_LOG
    - echo "Проект: $CI_PROJECT_NAME" >> $MERGE_LOG
    - echo "Коммит: $CI_COMMIT_SHORT_SHA" >> $MERGE_LOG
    - echo "Ветка: $CI_COMMIT_REF_NAME" >> $MERGE_LOG
    - echo "Запущено: $(date)" >> $MERGE_LOG
    - echo "=================" >> $MERGE_LOG
  script:
    - echo "Выполняю кастомные проверки"
  after_script:
    - |
      echo "" >> $MERGE_LOG
      echo "=== СТАТИСТИКА ===" >> $MERGE_LOG
      echo "Завершено: $(date)" >> $MERGE_LOG
      echo "Статус: $?" >> $MERGE_LOG
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - $MERGE_LOG
    when: always
    expire_in: 30 days

